server:
  port: 8080
spring:
  jpa:
    generate-ddl: true
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/BlackHole
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver


